apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: lamp
data:
  master.cnf: |
    [mysqld]
    log-bin=mysql-bin
    server-id=1
    binlog_format=row
    gtid_mode=on
    enforce_gtid_consistency=on
  slave.cnf: |
    [mysqld]
    server-id=2
    binlog_format=row
    gtid_mode=on
    enforce_gtid_consistency=on
    read_only=1
  init.sql: |
    CREATE USER 'replication'@'%' IDENTIFIED BY 'Lhj230200601';
    GRANT REPLICATION SLAVE ON *.* TO 'replication'@'%';
    FLUSH PRIVILEGES;
